version: "3.8"

services:
  prometheus:
    image: "prom/prometheus"
    restart: always
    networks:
      - prometheus
    ports: 
      - 9092:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
  pushgateway:
    image: "prom/pushgateway"
    restart: always
    networks:
      - prometheus
  grafana:
    image: "grafana/grafana"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    ports:
      - 9093:3000
    networks:
      - prometheus
  keyboard:
    build: .
    depends_on:
      - pushgateway
    restart: always
    command: metrics -p "http://pushgateway:9091" /dev/ttyACM0
    networks:
      - prometheus
    volumes:
      - /dev/ttyACM0:/dev/ttyACM0
    privileged: true

networks:
  prometheus:

volumes:
  prometheus:
  grafana_data:
